name: Clear Notebook Outputs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clear-notebooks:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed to push commits

    steps:
      - name: Hello, is this workflow running?
        run: echo "✅ workflow triggered on $(date)"
        
      # 1) Check out the full history so we can commit back
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true 

      # 2) Install Python and Jupyter tooling
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbconvert & notebook
        run: pip install notebook nbconvert

      # 3) Clear outputs from every .ipynb file
      - name: Clear notebook outputs
        run: |
          find . -type f -name "*.ipynb" -not -path "./.git/*" -print0 \
            | xargs -0 jupyter nbconvert --clear-output --inplace

      # Add this step before the commit step
      - name: Check for changes
        run: |
          git status
          git diff --name-only
          echo "Files that would be changed:"
          find . -name "*.ipynb" -exec echo "Processing: {}" \; -exec jupyter nbconvert --clear-output --to notebook --stdout {} \; > /dev/null

      # 4) Commit & push any changes
      - name: Auto‑commit cleared notebooks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: clear all notebook outputs"
          file_pattern: "**/*.ipynb"
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
